host: 0.0.0.0
port: 4000

# ----
# Site

title: MDwalks EXI cardio
url: "https://exi.mdwalks.net"
baseurl:
google_analytics_key:
google_maps_javascript_api_key:
disqus_shortname:

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: 심혈관질환 환자의 치료경로를 모니터링하고, 개인별 위험도를 분석하는 인공지능 SW입니다.
author:
  name:
  email:
  twitter: # twitter username without the @ symbol
social:
  name: MDwalks-EXI cardio
  links:
    - https://github.com/linewalks/MDwalks-EXI-Cardio

# -----
# Build

timezone: Etc/UTC

paginate: 10
paginate_path: "/blog/:num/"
permalink: pretty

defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"
  -
    scope:
      path: "index.html"
    values:
      layout: "default"
  -
    scope:
      path: "contact.html"
    values:
      full_width: true

jekyll-archives:
  enabled:
    - categories

plugins:
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

# -----------
# CloudCannon

social_icons:
  - Facebook
  - LinkedIn

_comments:
  map: Update the map location and display settings.
  latitude: Coordinates for the center marker on the map.
  longitude: Coordinates for the center marker on the map.
  zoom: The zoom level for the map.
  highlight: Emphasis the text
  color: The background colour used in the plan name and call to action.
  new_window: Open link in new window
